// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mtkovzpwqmtqngabepox.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10a292enB3cW10cW5nYWJlcG94Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NDQxMTgsImV4cCI6MjA2MDIyMDExOH0.7LwSRILct4CojjZPJ7gm9RpKjSp6d24MDJQNHRt2Tyk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);